<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="20" passed="0" failed="20" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-11-20T11:56:00 PKT" name="Default suite" finished-at="2019-11-20T11:56:31 PKT" duration-ms="31630">
    <groups>
    </groups>
    <test started-at="2019-11-20T11:56:00 PKT" name="Default test" finished-at="2019-11-20T11:56:31 PKT" duration-ms="31630">
      <class name="TesClass">
        <test-method signature="verify()[pri:1, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:00 PKT" name="verify" finished-at="2019-11-20T11:56:31 PKT" duration-ms="31195" status="FAIL">
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-11-20 11:56:30.645 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe69822680 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-11-20 11:56:30.646 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe694f5450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2019-11-20 11:56:30.668 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Beginning test session WebDriverAgentRunner-B543F20A-FF44-4514-B4BC-F9DD114E70EC at 2019-11-20 11:56:30.667 with Xcode 10G8 on target üì±<DVTiOSDevice (0x7fbe69c58340), Muhammad‚Äôs iPhone, iPhone, 12.1.2 (16C101), 240476512a6dd29a2f82fc8211ef4ea1bf6b5891> {
deviceSerialNumber:         F4RNJYTXG5MD
identifier:                 240476512a6dd29a2f82fc8211ef4ea1bf6b5891
deviceClass:                iPhone
deviceName:                 Muhammad‚Äôs iPhone
deviceIdentifier:           240476512a6dd29a2f82fc8211ef4ea1bf6b5891
productVersion:             12.1.2
buildVersion:               16C101
deviceSoftwareVersion:      12.1.2 (16C101)
deviceArchitecture:         arm64
deviceTotalCapacity:        9672060928
deviceAvailableCapacity:    3683008512
deviceIsTransient:          NO
ignored:                    NO
deviceIsBusy:               NO
deviceIsPaired:             YES
deviceIsActivated:          YES
deviceActivationState:      Activated
isPasscodeLocked:           NO
deviceType:                 <DVTDeviceType:0x7fbe69683ff0 Xcode.DeviceType.iPhone>
supportedDeviceFamilies:    (
    1
)
applications:              (null)
provisioningProfiles:      (null)
hasInternalSupport:        NO
isSupportedOS:             YES
developerDiskMountError:   (null)
(null)
bootArgs:                  (null)
nextBootArgs:              (null)
connected:                 yes
isWirelessEnabled:         no
connectionType:            direct
hostname:                  (null)
bonjourServiceName:        a8:5b:78:55:8f:ba@fe80::aa5b:78ff:fe55:8fba._apple-mobdev2._tcp.local.
} (12.1.2 (16C101))
2019-11-20 11:56:30.670 xcodebuild[13257:91576]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-7D5AEC7C-812E-4EC1-8B99-60B5AD94B1C9/WebDriverAgentRunner-D87674CE-77E8-40BB-ABEA-300A18EDB936/Session-WebDriverAgentRunner-2019-11-20_115630-PJAmys.log
2019-11-20 11:56:30.887 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 elapsed -- Testing started completed.
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 sec, +0.248 sec -- end
2019-11-20 11:56:30.909 xcodebuild[13257:91575] Error Domain=NSCocoaErrorDomain Code=260 "The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe693a8da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Testing failed:
No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "BNL4VQ2576" with a private key was found. (in target 'WebDriverAgentLib')
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file. The file doesn‚Äôt exist. (Underlying error: The operation couldn‚Äôt be completed. No such file or directory)))
Test session results and logs:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
** TEST EXECUTE FAILED **
Testing started on 'Muhammad‚Äôs iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Admins-MacBook-Pro.local', ip: 'fe80:0:0:0:c50:7222:ab71:2cb5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-11-20 11:56:30.645 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe69822680 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-11-20 11:56:30.646 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe694f5450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2019-11-20 11:56:30.668 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Beginning test session WebDriverAgentRunner-B543F20A-FF44-4514-B4BC-F9DD114E70EC at 2019-11-20 11:56:30.667 with Xcode 10G8 on target üì±<DVTiOSDevice (0x7fbe69c58340), Muhammad‚Äôs iPhone, iPhone, 12.1.2 (16C101), 240476512a6dd29a2f82fc8211ef4ea1bf6b5891> {
deviceSerialNumber:         F4RNJYTXG5MD
identifier:                 240476512a6dd29a2f82fc8211ef4ea1bf6b5891
deviceClass:                iPhone
deviceName:                 Muhammad‚Äôs iPhone
deviceIdentifier:           240476512a6dd29a2f82fc8211ef4ea1bf6b5891
productVersion:             12.1.2
buildVersion:               16C101
deviceSoftwareVersion:      12.1.2 (16C101)
deviceArchitecture:         arm64
deviceTotalCapacity:        9672060928
deviceAvailableCapacity:    3683008512
deviceIsTransient:          NO
ignored:                    NO
deviceIsBusy:               NO
deviceIsPaired:             YES
deviceIsActivated:          YES
deviceActivationState:      Activated
isPasscodeLocked:           NO
deviceType:                 <DVTDeviceType:0x7fbe69683ff0 Xcode.DeviceType.iPhone>
supportedDeviceFamilies:    (
    1
)
applications:              (null)
provisioningProfiles:      (null)
hasInternalSupport:        NO
isSupportedOS:             YES
developerDiskMountError:   (null)
(null)
bootArgs:                  (null)
nextBootArgs:              (null)
connected:                 yes
isWirelessEnabled:         no
connectionType:            direct
hostname:                  (null)
bonjourServiceName:        a8:5b:78:55:8f:ba@fe80::aa5b:78ff:fe55:8fba._apple-mobdev2._tcp.local.
} (12.1.2 (16C101))
2019-11-20 11:56:30.670 xcodebuild[13257:91576]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-7D5AEC7C-812E-4EC1-8B99-60B5AD94B1C9/WebDriverAgentRunner-D87674CE-77E8-40BB-ABEA-300A18EDB936/Session-WebDriverAgentRunner-2019-11-20_115630-PJAmys.log
2019-11-20 11:56:30.887 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 elapsed -- Testing started completed.
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 sec, +0.248 sec -- end
2019-11-20 11:56:30.909 xcodebuild[13257:91575] Error Domain=NSCocoaErrorDomain Code=260 "The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe693a8da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Testing failed:
No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "BNL4VQ2576" with a private key was found. (in target 'WebDriverAgentLib')
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file. The file doesn‚Äôt exist. (Underlying error: The operation couldn‚Äôt be completed. No such file or directory)))
Test session results and logs:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
** TEST EXECUTE FAILED **
Testing started on 'Muhammad‚Äôs iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Admins-MacBook-Pro.local', ip: 'fe80:0:0:0:c50:7222:ab71:2cb5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
Driver info: driver.version: IOSDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-11-20 11:56:30.645 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe69822680 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-11-20 11:56:30.646 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe694f5450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2019-11-20 11:56:30.668 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Beginning test session WebDriverAgentRunner-B543F20A-FF44-4514-B4BC-F9DD114E70EC at 2019-11-20 11:56:30.667 with Xcode 10G8 on target üì±<DVTiOSDevice (0x7fbe69c58340), Muhammad‚Äôs iPhone, iPhone, 12.1.2 (16C101), 240476512a6dd29a2f82fc8211ef4ea1bf6b5891> {
deviceSerialNumber:         F4RNJYTXG5MD
identifier:                 240476512a6dd29a2f82fc8211ef4ea1bf6b5891
deviceClass:                iPhone
deviceName:                 Muhammad‚Äôs iPhone
deviceIdentifier:           240476512a6dd29a2f82fc8211ef4ea1bf6b5891
productVersion:             12.1.2
buildVersion:               16C101
deviceSoftwareVersion:      12.1.2 (16C101)
deviceArchitecture:         arm64
deviceTotalCapacity:        9672060928
deviceAvailableCapacity:    3683008512
deviceIsTransient:          NO
ignored:                    NO
deviceIsBusy:               NO
deviceIsPaired:             YES
deviceIsActivated:          YES
deviceActivationState:      Activated
isPasscodeLocked:           NO
deviceType:                 <DVTDeviceType:0x7fbe69683ff0 Xcode.DeviceType.iPhone>
supportedDeviceFamilies:    (
    1
)
applications:              (null)
provisioningProfiles:      (null)
hasInternalSupport:        NO
isSupportedOS:             YES
developerDiskMountError:   (null)
(null)
bootArgs:                  (null)
nextBootArgs:              (null)
connected:                 yes
isWirelessEnabled:         no
connectionType:            direct
hostname:                  (null)
bonjourServiceName:        a8:5b:78:55:8f:ba@fe80::aa5b:78ff:fe55:8fba._apple-mobdev2._tcp.local.
} (12.1.2 (16C101))
2019-11-20 11:56:30.670 xcodebuild[13257:91576]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-7D5AEC7C-812E-4EC1-8B99-60B5AD94B1C9/WebDriverAgentRunner-D87674CE-77E8-40BB-ABEA-300A18EDB936/Session-WebDriverAgentRunner-2019-11-20_115630-PJAmys.log
2019-11-20 11:56:30.887 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 elapsed -- Testing started completed.
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 sec, +0.248 sec -- end
2019-11-20 11:56:30.909 xcodebuild[13257:91575] Error Domain=NSCocoaErrorDomain Code=260 "The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe693a8da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Testing failed:
No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "BNL4VQ2576" with a private key was found. (in target 'WebDriverAgentLib')
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file. The file doesn‚Äôt exist. (Underlying error: The operation couldn‚Äôt be completed. No such file or directory)))
Test session results and logs:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
** TEST EXECUTE FAILED **
Testing started on 'Muhammad‚Äôs iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Admins-MacBook-Pro.local', ip: 'fe80:0:0:0:c50:7222:ab71:2cb5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-11-20 11:56:30.645 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe69822680 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-11-20 11:56:30.646 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe694f5450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2019-11-20 11:56:30.668 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Beginning test session WebDriverAgentRunner-B543F20A-FF44-4514-B4BC-F9DD114E70EC at 2019-11-20 11:56:30.667 with Xcode 10G8 on target üì±<DVTiOSDevice (0x7fbe69c58340), Muhammad‚Äôs iPhone, iPhone, 12.1.2 (16C101), 240476512a6dd29a2f82fc8211ef4ea1bf6b5891> {
deviceSerialNumber:         F4RNJYTXG5MD
identifier:                 240476512a6dd29a2f82fc8211ef4ea1bf6b5891
deviceClass:                iPhone
deviceName:                 Muhammad‚Äôs iPhone
deviceIdentifier:           240476512a6dd29a2f82fc8211ef4ea1bf6b5891
productVersion:             12.1.2
buildVersion:               16C101
deviceSoftwareVersion:      12.1.2 (16C101)
deviceArchitecture:         arm64
deviceTotalCapacity:        9672060928
deviceAvailableCapacity:    3683008512
deviceIsTransient:          NO
ignored:                    NO
deviceIsBusy:               NO
deviceIsPaired:             YES
deviceIsActivated:          YES
deviceActivationState:      Activated
isPasscodeLocked:           NO
deviceType:                 <DVTDeviceType:0x7fbe69683ff0 Xcode.DeviceType.iPhone>
supportedDeviceFamilies:    (
    1
)
applications:              (null)
provisioningProfiles:      (null)
hasInternalSupport:        NO
isSupportedOS:             YES
developerDiskMountError:   (null)
(null)
bootArgs:                  (null)
nextBootArgs:              (null)
connected:                 yes
isWirelessEnabled:         no
connectionType:            direct
hostname:                  (null)
bonjourServiceName:        a8:5b:78:55:8f:ba@fe80::aa5b:78ff:fe55:8fba._apple-mobdev2._tcp.local.
} (12.1.2 (16C101))
2019-11-20 11:56:30.670 xcodebuild[13257:91576]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-7D5AEC7C-812E-4EC1-8B99-60B5AD94B1C9/WebDriverAgentRunner-D87674CE-77E8-40BB-ABEA-300A18EDB936/Session-WebDriverAgentRunner-2019-11-20_115630-PJAmys.log
2019-11-20 11:56:30.887 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 elapsed -- Testing started completed.
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 sec, +0.248 sec -- end
2019-11-20 11:56:30.909 xcodebuild[13257:91575] Error Domain=NSCocoaErrorDomain Code=260 "The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe693a8da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Testing failed:
No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "BNL4VQ2576" with a private key was found. (in target 'WebDriverAgentLib')
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file. The file doesn‚Äôt exist. (Underlying error: The operation couldn‚Äôt be completed. No such file or directory)))
Test session results and logs:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
** TEST EXECUTE FAILED **
Testing started on 'Muhammad‚Äôs iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Admins-MacBook-Pro.local', ip: 'fe80:0:0:0:c50:7222:ab71:2cb5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
Driver info: driver.version: IOSDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:208)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:217)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:86)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:96)
at io.appium.java_client.ios.IOSDriver.<init>(IOSDriver.java:92)
at TesClass.verify(TesClass.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:186)
... 42 more
Caused by: org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-11-20 11:56:30.645 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe69822680 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-11-20 11:56:30.646 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe694f5450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2019-11-20 11:56:30.668 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Beginning test session WebDriverAgentRunner-B543F20A-FF44-4514-B4BC-F9DD114E70EC at 2019-11-20 11:56:30.667 with Xcode 10G8 on target üì±<DVTiOSDevice (0x7fbe69c58340), Muhammad‚Äôs iPhone, iPhone, 12.1.2 (16C101), 240476512a6dd29a2f82fc8211ef4ea1bf6b5891> {
deviceSerialNumber:         F4RNJYTXG5MD
identifier:                 240476512a6dd29a2f82fc8211ef4ea1bf6b5891
deviceClass:                iPhone
deviceName:                 Muhammad‚Äôs iPhone
deviceIdentifier:           240476512a6dd29a2f82fc8211ef4ea1bf6b5891
productVersion:             12.1.2
buildVersion:               16C101
deviceSoftwareVersion:      12.1.2 (16C101)
deviceArchitecture:         arm64
deviceTotalCapacity:        9672060928
deviceAvailableCapacity:    3683008512
deviceIsTransient:          NO
ignored:                    NO
deviceIsBusy:               NO
deviceIsPaired:             YES
deviceIsActivated:          YES
deviceActivationState:      Activated
isPasscodeLocked:           NO
deviceType:                 <DVTDeviceType:0x7fbe69683ff0 Xcode.DeviceType.iPhone>
supportedDeviceFamilies:    (
    1
)
applications:              (null)
provisioningProfiles:      (null)
hasInternalSupport:        NO
isSupportedOS:             YES
developerDiskMountError:   (null)
(null)
bootArgs:                  (null)
nextBootArgs:              (null)
connected:                 yes
isWirelessEnabled:         no
connectionType:            direct
hostname:                  (null)
bonjourServiceName:        a8:5b:78:55:8f:ba@fe80::aa5b:78ff:fe55:8fba._apple-mobdev2._tcp.local.
} (12.1.2 (16C101))
2019-11-20 11:56:30.670 xcodebuild[13257:91576]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-7D5AEC7C-812E-4EC1-8B99-60B5AD94B1C9/WebDriverAgentRunner-D87674CE-77E8-40BB-ABEA-300A18EDB936/Session-WebDriverAgentRunner-2019-11-20_115630-PJAmys.log
2019-11-20 11:56:30.887 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 elapsed -- Testing started completed.
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 sec, +0.248 sec -- end
2019-11-20 11:56:30.909 xcodebuild[13257:91575] Error Domain=NSCocoaErrorDomain Code=260 "The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe693a8da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Testing failed:
No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "BNL4VQ2576" with a private key was found. (in target 'WebDriverAgentLib')
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file. The file doesn‚Äôt exist. (Underlying error: The operation couldn‚Äôt be completed. No such file or directory)))
Test session results and logs:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
** TEST EXECUTE FAILED **
Testing started on 'Muhammad‚Äôs iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Admins-MacBook-Pro.local', ip: 'fe80:0:0:0:c50:7222:ab71:2cb5%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '12.0.2'
Driver info: driver.version: IOSDriver
remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:

2019-11-20 11:56:30.645 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe69822680 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2019-11-20 11:56:30.646 xcodebuild[13257:91605] Error writing xctestrun file: Error Domain=NSCocoaErrorDomain Code=4 "The folder ‚ÄúWebDriverAgentRunner_iphoneos12.4-arm64.xctestrun‚Äù doesn‚Äôt exist." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/WebDriverAgentRunner_iphoneos12.4-arm64.xctestrun, NSUserStringVariant=Folder, NSUnderlyingError=0x7fbe694f5450 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
** TEST BUILD FAILED **
2019-11-20 11:56:30.668 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Beginning test session WebDriverAgentRunner-B543F20A-FF44-4514-B4BC-F9DD114E70EC at 2019-11-20 11:56:30.667 with Xcode 10G8 on target üì±<DVTiOSDevice (0x7fbe69c58340), Muhammad‚Äôs iPhone, iPhone, 12.1.2 (16C101), 240476512a6dd29a2f82fc8211ef4ea1bf6b5891> {
deviceSerialNumber:         F4RNJYTXG5MD
identifier:                 240476512a6dd29a2f82fc8211ef4ea1bf6b5891
deviceClass:                iPhone
deviceName:                 Muhammad‚Äôs iPhone
deviceIdentifier:           240476512a6dd29a2f82fc8211ef4ea1bf6b5891
productVersion:             12.1.2
buildVersion:               16C101
deviceSoftwareVersion:      12.1.2 (16C101)
deviceArchitecture:         arm64
deviceTotalCapacity:        9672060928
deviceAvailableCapacity:    3683008512
deviceIsTransient:          NO
ignored:                    NO
deviceIsBusy:               NO
deviceIsPaired:             YES
deviceIsActivated:          YES
deviceActivationState:      Activated
isPasscodeLocked:           NO
deviceType:                 <DVTDeviceType:0x7fbe69683ff0 Xcode.DeviceType.iPhone>
supportedDeviceFamilies:    (
    1
)
applications:              (null)
provisioningProfiles:      (null)
hasInternalSupport:        NO
isSupportedOS:             YES
developerDiskMountError:   (null)
(null)
bootArgs:                  (null)
nextBootArgs:              (null)
connected:                 yes
isWirelessEnabled:         no
connectionType:            direct
hostname:                  (null)
bonjourServiceName:        a8:5b:78:55:8f:ba@fe80::aa5b:78ff:fe55:8fba._apple-mobdev2._tcp.local.
} (12.1.2 (16C101))
2019-11-20 11:56:30.670 xcodebuild[13257:91576]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult/2_Test/Diagnostics/WebDriverAgentRunner-7D5AEC7C-812E-4EC1-8B99-60B5AD94B1C9/WebDriverAgentRunner-D87674CE-77E8-40BB-ABEA-300A18EDB936/Session-WebDriverAgentRunner-2019-11-20_115630-PJAmys.log
2019-11-20 11:56:30.887 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: (B543F20A-FF44-4514-B4BC-F9DD114E70EC) Finished requesting crash reports. Continuing with testing.
*** If you believe this error represents a bug, please attach the result bundle at /Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 elapsed -- Testing started completed.
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-11-20 11:56:30.908 xcodebuild[13257:91575] [MT] IDETestOperationsObserverDebug: 0.248 sec, +0.248 sec -- end
2019-11-20 11:56:30.909 xcodebuild[13257:91575] Error Domain=NSCocoaErrorDomain Code=260 "The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file." UserInfo={NSFilePath=/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fbe693a8da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Testing failed:
No profiles for 'com.facebook.WebDriverAgentRunner' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.facebook.WebDriverAgentRunner'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'WebDriverAgentRunner')
No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "BNL4VQ2576" with a private key was found. (in target 'WebDriverAgentLib')
WebDriverAgentRunner:
WebDriverAgentRunner-Runner.app encountered an error (Failed to install or launch the test runner. (Underlying error: The file ‚ÄúWebDriverAgentRunner-Runner.app‚Äù couldn‚Äôt be opened because there is no such file. The file doesn‚Äôt exist. (Underlying error: The operation couldn‚Äôt be completed. No such file or directory)))
Test session results and logs:
/Users/ahmsam/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Logs/Test/Test-WebDriverAgentRunner-2019.11.20_11-56-30-+0500.xcresult
** TEST EXECUTE FAILED **
Testing started on 'Muhammad‚Äôs iPhone'. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:826:9)
    at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:447:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
... 47 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method signature="test1()[pri:2, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test1" finished-at="2019-11-20T11:56:31 PKT" duration-ms="246" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field LoginPage.firstPopUp to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field LoginPage.firstPopUp to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at LoginPage.<init>(LoginPage.java:21)
at TesClass.test1(TesClass.java:119)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test3()[pri:3, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test3" finished-at="2019-11-20T11:56:31 PKT" duration-ms="3" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field LoginPage.firstPopUp to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field LoginPage.firstPopUp to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at LoginPage.<init>(LoginPage.java:21)
at TesClass.test3(TesClass.java:132)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method signature="test4()[pri:4, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test4" finished-at="2019-11-20T11:56:31 PKT" duration-ms="3" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field LoginPage.firstPopUp to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field LoginPage.firstPopUp to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at LoginPage.<init>(LoginPage.java:21)
at TesClass.test4(TesClass.java:145)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test4 -->
        <test-method signature="test5()[pri:5, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test5" finished-at="2019-11-20T11:56:31 PKT" duration-ms="4" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field MainPage.Training_Guide_Btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field MainPage.Training_Guide_Btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at MainPage.<init>(MainPage.java:23)
at TesClass.test5(TesClass.java:159)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test5 -->
        <test-method signature="test6()[pri:6, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test6" finished-at="2019-11-20T11:56:31 PKT" duration-ms="4" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test6(TesClass.java:173)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
        <test-method signature="test7()[pri:7, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test7" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test7(TesClass.java:189)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
        <test-method signature="test8()[pri:8, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test8" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test8(TesClass.java:201)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test8 -->
        <test-method signature="test9()[pri:9, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test9" finished-at="2019-11-20T11:56:31 PKT" duration-ms="3" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test9(TesClass.java:213)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test9 -->
        <test-method signature="test10()[pri:10, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test10" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test10(TesClass.java:225)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test10 -->
        <test-method signature="test11()[pri:11, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test11" finished-at="2019-11-20T11:56:31 PKT" duration-ms="4" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test11(TesClass.java:237)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test11 -->
        <test-method signature="test12()[pri:12, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test12" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test12(TesClass.java:249)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test12 -->
        <test-method signature="test13()[pri:13, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test13" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test13(TesClass.java:261)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test13 -->
        <test-method signature="test14()[pri:14, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test14" finished-at="2019-11-20T11:56:31 PKT" duration-ms="4" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test14(TesClass.java:273)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test14 -->
        <test-method signature="test15()[pri:15, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test15" finished-at="2019-11-20T11:56:31 PKT" duration-ms="1" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test15(TesClass.java:286)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test15 -->
        <test-method signature="test16()[pri:16, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test16" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test16(TesClass.java:298)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test16 -->
        <test-method signature="test17()[pri:17, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test17" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test17(TesClass.java:309)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test17 -->
        <test-method signature="test18()[pri:18, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test18" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test18(TesClass.java:320)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test18 -->
        <test-method signature="test19()[pri:19, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test19" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test19(TesClass.java:331)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test19 -->
        <test-method signature="test21()[pri:21, instance:TesClass@5e5d171f]" started-at="2019-11-20T11:56:31 PKT" name="test21" finished-at="2019-11-20T11:56:31 PKT" duration-ms="2" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Can not set io.appium.java_client.MobileElement field ProgrammesPage.continue_btn to org.openqa.selenium.remote.RemoteWebElement$$EnhancerByCGLIB$$d27c0df4
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
at java.base/jdk.internal.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
at java.base/java.lang.reflect.Field.set(Field.java:780)
at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
at ProgrammesPage.<init>(ProgrammesPage.java:21)
at TesClass.test21(TesClass.java:353)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test21 -->
      </class> <!-- TesClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
